const TEAM_LIMIT = 10;
const FULL_SIGNAL_COUNT = 30;
const SIGNAL_TYPE_ALPHA = "ALPHA";
const SIGNAL_TYPE_NOISE = "NOISE";
const DECISION_TRADE = "TRADE";
const DECISION_IGNORE = "IGNORE";
const SIGNAL_VALUE_MIN = 100;
const SIGNAL_VALUE_MAX = 1000;
const DEFAULT_PORT = 3000;
const DEFAULT_ROUND_DURATION_MS = 10000;
const DEFAULT_TOTAL_ROUNDS = 30;
const GRACE_WINDOW_MS = 100;
const MAX_ROUND_DURATION_MS = 60000;
const ADMIN_ACTION_RATE_LIMIT_MS = 500;
const AUDIT_LOG_LIMIT = 200;

const GAME_PHASES = Object.freeze({
  IDLE: "idle",
  LIVE: "live",
  PAUSED: "paused",
  RESULTS: "results",
  FINISHED: "finished",
});

module.exports = {
  ADMIN_ACTION_RATE_LIMIT_MS,
  AUDIT_LOG_LIMIT,
  DECISION_IGNORE,
  DECISION_TRADE,
  DEFAULT_PORT,
  DEFAULT_ROUND_DURATION_MS,
  DEFAULT_TOTAL_ROUNDS,
  FULL_SIGNAL_COUNT,
  GAME_PHASES,
  GRACE_WINDOW_MS,
  MAX_ROUND_DURATION_MS,
  SIGNAL_TYPE_ALPHA,
  SIGNAL_TYPE_NOISE,
  SIGNAL_VALUE_MAX,
  SIGNAL_VALUE_MIN,
  TEAM_LIMIT,
};
