const TEAM_LIMIT = 12;
const TOTAL_ROUNDS = 6;
const COMPANY_IDS = ["a", "b", "c", "d", "e", "f"];
const STARTING_PURSE_VALUE = 100000;
const DEFAULT_PORT = 3000;
const DEFAULT_ROUND_DURATION_MS = 60000;
const MAX_ROUND_DURATION_MS = 3600000;
const GRACE_WINDOW_MS = 200;
const ADMIN_ACTION_RATE_LIMIT_MS = 500;
const AUDIT_LOG_LIMIT = 200;
const DEFAULT_HOST = "0.0.0.0";
const DEFAULT_SOCKET_PING_INTERVAL_MS = 25000;
const DEFAULT_SOCKET_PING_TIMEOUT_MS = 20000;
const DEFAULT_SCHEDULER_INTERVAL_MS = 1000;

const GAME_PHASES = Object.freeze({
  IDLE: "idle",
  LIVE: "live",
  PAUSED: "paused",
  RESULTS: "results",
  FINISHED: "finished",
});

module.exports = {
  ADMIN_ACTION_RATE_LIMIT_MS,
  AUDIT_LOG_LIMIT,
  COMPANY_IDS,
  DEFAULT_HOST,
  DEFAULT_PORT,
  DEFAULT_ROUND_DURATION_MS,
  DEFAULT_SCHEDULER_INTERVAL_MS,
  DEFAULT_SOCKET_PING_INTERVAL_MS,
  DEFAULT_SOCKET_PING_TIMEOUT_MS,
  GAME_PHASES,
  GRACE_WINDOW_MS,
  MAX_ROUND_DURATION_MS,
  STARTING_PURSE_VALUE,
  TEAM_LIMIT,
  TOTAL_ROUNDS,
};
